// Code generated by protoc-gen-go-lite. DO NOT EDIT.
// protoc-gen-go-lite version: (devel)
// source: client_model/go/metrics.proto

package io_prometheus_client

import (
	strconv "strconv"

	timestamppb "github.com/aperturerobotics/protobuf-go-lite/types/known/timestamppb"
)

// Copyright 2013 Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

type MetricType int32

const (
	// COUNTER must use the Metric field "counter".
	MetricType_COUNTER MetricType = 0
	// GAUGE must use the Metric field "gauge".
	MetricType_GAUGE MetricType = 1
	// SUMMARY must use the Metric field "summary".
	MetricType_SUMMARY MetricType = 2
	// UNTYPED must use the Metric field "untyped".
	MetricType_UNTYPED MetricType = 3
	// HISTOGRAM must use the Metric field "histogram".
	MetricType_HISTOGRAM MetricType = 4
	// GAUGE_HISTOGRAM must use the Metric field "histogram".
	MetricType_GAUGE_HISTOGRAM MetricType = 5
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "COUNTER",
		1: "GAUGE",
		2: "SUMMARY",
		3: "UNTYPED",
		4: "HISTOGRAM",
		5: "GAUGE_HISTOGRAM",
	}
	MetricType_value = map[string]int32{
		"COUNTER":         0,
		"GAUGE":           1,
		"SUMMARY":         2,
		"UNTYPED":         3,
		"HISTOGRAM":       4,
		"GAUGE_HISTOGRAM": 5,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	name, valid := MetricType_name[int32(x)]
	if valid {
		return name
	}
	return strconv.Itoa(int(x))
}

type LabelPair struct {
	unknownFields []byte
	Name          *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Value         *string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (x *LabelPair) Reset() {
	*x = LabelPair{}
}

func (*LabelPair) ProtoMessage() {}

func (x *LabelPair) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *LabelPair) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type Gauge struct {
	unknownFields []byte
	Value         *float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
}

func (x *Gauge) Reset() {
	*x = Gauge{}
}

func (*Gauge) ProtoMessage() {}

func (x *Gauge) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type Counter struct {
	unknownFields    []byte
	Value            *float64               `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
	Exemplar         *Exemplar              `protobuf:"bytes,2,opt,name=exemplar" json:"exemplar,omitempty"`
	CreatedTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_timestamp,json=createdTimestamp" json:"createdTimestamp,omitempty"`
}

func (x *Counter) Reset() {
	*x = Counter{}
}

func (*Counter) ProtoMessage() {}

func (x *Counter) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Counter) GetExemplar() *Exemplar {
	if x != nil {
		return x.Exemplar
	}
	return nil
}

func (x *Counter) GetCreatedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTimestamp
	}
	return nil
}

type Quantile struct {
	unknownFields []byte
	Quantile      *float64 `protobuf:"fixed64,1,opt,name=quantile" json:"quantile,omitempty"`
	Value         *float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (x *Quantile) Reset() {
	*x = Quantile{}
}

func (*Quantile) ProtoMessage() {}

func (x *Quantile) GetQuantile() float64 {
	if x != nil && x.Quantile != nil {
		return *x.Quantile
	}
	return 0
}

func (x *Quantile) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type Summary struct {
	unknownFields    []byte
	SampleCount      *uint64                `protobuf:"varint,1,opt,name=sample_count,json=sampleCount" json:"sampleCount,omitempty"`
	SampleSum        *float64               `protobuf:"fixed64,2,opt,name=sample_sum,json=sampleSum" json:"sampleSum,omitempty"`
	Quantile         []*Quantile            `protobuf:"bytes,3,rep,name=quantile" json:"quantile,omitempty"`
	CreatedTimestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_timestamp,json=createdTimestamp" json:"createdTimestamp,omitempty"`
}

func (x *Summary) Reset() {
	*x = Summary{}
}

func (*Summary) ProtoMessage() {}

func (x *Summary) GetSampleCount() uint64 {
	if x != nil && x.SampleCount != nil {
		return *x.SampleCount
	}
	return 0
}

func (x *Summary) GetSampleSum() float64 {
	if x != nil && x.SampleSum != nil {
		return *x.SampleSum
	}
	return 0
}

func (x *Summary) GetQuantile() []*Quantile {
	if x != nil {
		return x.Quantile
	}
	return nil
}

func (x *Summary) GetCreatedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTimestamp
	}
	return nil
}

type Untyped struct {
	unknownFields []byte
	Value         *float64 `protobuf:"fixed64,1,opt,name=value" json:"value,omitempty"`
}

func (x *Untyped) Reset() {
	*x = Untyped{}
}

func (*Untyped) ProtoMessage() {}

func (x *Untyped) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type Histogram struct {
	unknownFields    []byte
	SampleCount      *uint64                `protobuf:"varint,1,opt,name=sample_count,json=sampleCount" json:"sampleCount,omitempty"`
	SampleCountFloat *float64               `protobuf:"fixed64,4,opt,name=sample_count_float,json=sampleCountFloat" json:"sampleCountFloat,omitempty"`
	SampleSum        *float64               `protobuf:"fixed64,2,opt,name=sample_sum,json=sampleSum" json:"sampleSum,omitempty"`
	Bucket           []*Bucket              `protobuf:"bytes,3,rep,name=bucket" json:"bucket,omitempty"`
	CreatedTimestamp *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_timestamp,json=createdTimestamp" json:"createdTimestamp,omitempty"`
	Schema           *int32                 `protobuf:"zigzag32,5,opt,name=schema" json:"schema,omitempty"`
	ZeroThreshold    *float64               `protobuf:"fixed64,6,opt,name=zero_threshold,json=zeroThreshold" json:"zeroThreshold,omitempty"`
	ZeroCount        *uint64                `protobuf:"varint,7,opt,name=zero_count,json=zeroCount" json:"zeroCount,omitempty"`
	ZeroCountFloat   *float64               `protobuf:"fixed64,8,opt,name=zero_count_float,json=zeroCountFloat" json:"zeroCountFloat,omitempty"`
	NegativeSpan     []*BucketSpan          `protobuf:"bytes,9,rep,name=negative_span,json=negativeSpan" json:"negativeSpan,omitempty"`
	NegativeDelta    []int64                `protobuf:"zigzag64,10,rep,name=negative_delta,json=negativeDelta" json:"negativeDelta,omitempty"`
	NegativeCount    []float64              `protobuf:"fixed64,11,rep,name=negative_count,json=negativeCount" json:"negativeCount,omitempty"`
	PositiveSpan     []*BucketSpan          `protobuf:"bytes,12,rep,name=positive_span,json=positiveSpan" json:"positiveSpan,omitempty"`
	PositiveDelta    []int64                `protobuf:"zigzag64,13,rep,name=positive_delta,json=positiveDelta" json:"positiveDelta,omitempty"`
	PositiveCount    []float64              `protobuf:"fixed64,14,rep,name=positive_count,json=positiveCount" json:"positiveCount,omitempty"`
	Exemplars        []*Exemplar            `protobuf:"bytes,16,rep,name=exemplars" json:"exemplars,omitempty"`
}

func (x *Histogram) Reset() {
	*x = Histogram{}
}

func (*Histogram) ProtoMessage() {}

func (x *Histogram) GetSampleCount() uint64 {
	if x != nil && x.SampleCount != nil {
		return *x.SampleCount
	}
	return 0
}

func (x *Histogram) GetSampleCountFloat() float64 {
	if x != nil && x.SampleCountFloat != nil {
		return *x.SampleCountFloat
	}
	return 0
}

func (x *Histogram) GetSampleSum() float64 {
	if x != nil && x.SampleSum != nil {
		return *x.SampleSum
	}
	return 0
}

func (x *Histogram) GetBucket() []*Bucket {
	if x != nil {
		return x.Bucket
	}
	return nil
}

func (x *Histogram) GetCreatedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedTimestamp
	}
	return nil
}

func (x *Histogram) GetSchema() int32 {
	if x != nil && x.Schema != nil {
		return *x.Schema
	}
	return 0
}

func (x *Histogram) GetZeroThreshold() float64 {
	if x != nil && x.ZeroThreshold != nil {
		return *x.ZeroThreshold
	}
	return 0
}

func (x *Histogram) GetZeroCount() uint64 {
	if x != nil && x.ZeroCount != nil {
		return *x.ZeroCount
	}
	return 0
}

func (x *Histogram) GetZeroCountFloat() float64 {
	if x != nil && x.ZeroCountFloat != nil {
		return *x.ZeroCountFloat
	}
	return 0
}

func (x *Histogram) GetNegativeSpan() []*BucketSpan {
	if x != nil {
		return x.NegativeSpan
	}
	return nil
}

func (x *Histogram) GetNegativeDelta() []int64 {
	if x != nil {
		return x.NegativeDelta
	}
	return nil
}

func (x *Histogram) GetNegativeCount() []float64 {
	if x != nil {
		return x.NegativeCount
	}
	return nil
}

func (x *Histogram) GetPositiveSpan() []*BucketSpan {
	if x != nil {
		return x.PositiveSpan
	}
	return nil
}

func (x *Histogram) GetPositiveDelta() []int64 {
	if x != nil {
		return x.PositiveDelta
	}
	return nil
}

func (x *Histogram) GetPositiveCount() []float64 {
	if x != nil {
		return x.PositiveCount
	}
	return nil
}

func (x *Histogram) GetExemplars() []*Exemplar {
	if x != nil {
		return x.Exemplars
	}
	return nil
}

type Bucket struct {
	unknownFields        []byte
	CumulativeCount      *uint64   `protobuf:"varint,1,opt,name=cumulative_count,json=cumulativeCount" json:"cumulativeCount,omitempty"`
	CumulativeCountFloat *float64  `protobuf:"fixed64,4,opt,name=cumulative_count_float,json=cumulativeCountFloat" json:"cumulativeCountFloat,omitempty"`
	UpperBound           *float64  `protobuf:"fixed64,2,opt,name=upper_bound,json=upperBound" json:"upperBound,omitempty"`
	Exemplar             *Exemplar `protobuf:"bytes,3,opt,name=exemplar" json:"exemplar,omitempty"`
}

func (x *Bucket) Reset() {
	*x = Bucket{}
}

func (*Bucket) ProtoMessage() {}

func (x *Bucket) GetCumulativeCount() uint64 {
	if x != nil && x.CumulativeCount != nil {
		return *x.CumulativeCount
	}
	return 0
}

func (x *Bucket) GetCumulativeCountFloat() float64 {
	if x != nil && x.CumulativeCountFloat != nil {
		return *x.CumulativeCountFloat
	}
	return 0
}

func (x *Bucket) GetUpperBound() float64 {
	if x != nil && x.UpperBound != nil {
		return *x.UpperBound
	}
	return 0
}

func (x *Bucket) GetExemplar() *Exemplar {
	if x != nil {
		return x.Exemplar
	}
	return nil
}

type BucketSpan struct {
	unknownFields []byte
	Offset        *int32  `protobuf:"zigzag32,1,opt,name=offset" json:"offset,omitempty"`
	Length        *uint32 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
}

func (x *BucketSpan) Reset() {
	*x = BucketSpan{}
}

func (*BucketSpan) ProtoMessage() {}

func (x *BucketSpan) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *BucketSpan) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

type Exemplar struct {
	unknownFields []byte
	Label         []*LabelPair           `protobuf:"bytes,1,rep,name=label" json:"label,omitempty"`
	Value         *float64               `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (x *Exemplar) Reset() {
	*x = Exemplar{}
}

func (*Exemplar) ProtoMessage() {}

func (x *Exemplar) GetLabel() []*LabelPair {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Exemplar) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *Exemplar) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Metric struct {
	unknownFields []byte
	Label         []*LabelPair `protobuf:"bytes,1,rep,name=label" json:"label,omitempty"`
	Gauge         *Gauge       `protobuf:"bytes,2,opt,name=gauge" json:"gauge,omitempty"`
	Counter       *Counter     `protobuf:"bytes,3,opt,name=counter" json:"counter,omitempty"`
	Summary       *Summary     `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	Untyped       *Untyped     `protobuf:"bytes,5,opt,name=untyped" json:"untyped,omitempty"`
	Histogram     *Histogram   `protobuf:"bytes,7,opt,name=histogram" json:"histogram,omitempty"`
	TimestampMs   *int64       `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs" json:"timestampMs,omitempty"`
}

func (x *Metric) Reset() {
	*x = Metric{}
}

func (*Metric) ProtoMessage() {}

func (x *Metric) GetLabel() []*LabelPair {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *Metric) GetGauge() *Gauge {
	if x != nil {
		return x.Gauge
	}
	return nil
}

func (x *Metric) GetCounter() *Counter {
	if x != nil {
		return x.Counter
	}
	return nil
}

func (x *Metric) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Metric) GetUntyped() *Untyped {
	if x != nil {
		return x.Untyped
	}
	return nil
}

func (x *Metric) GetHistogram() *Histogram {
	if x != nil {
		return x.Histogram
	}
	return nil
}

func (x *Metric) GetTimestampMs() int64 {
	if x != nil && x.TimestampMs != nil {
		return *x.TimestampMs
	}
	return 0
}

type MetricFamily struct {
	unknownFields []byte
	Name          *string     `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Help          *string     `protobuf:"bytes,2,opt,name=help" json:"help,omitempty"`
	Type          *MetricType `protobuf:"varint,3,opt,name=type" json:"type,omitempty"`
	Metric        []*Metric   `protobuf:"bytes,4,rep,name=metric" json:"metric,omitempty"`
	Unit          *string     `protobuf:"bytes,5,opt,name=unit" json:"unit,omitempty"`
}

func (x *MetricFamily) Reset() {
	*x = MetricFamily{}
}

func (*MetricFamily) ProtoMessage() {}

func (x *MetricFamily) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *MetricFamily) GetHelp() string {
	if x != nil && x.Help != nil {
		return *x.Help
	}
	return ""
}

func (x *MetricFamily) GetType() MetricType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return MetricType_COUNTER
}

func (x *MetricFamily) GetMetric() []*Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *MetricFamily) GetUnit() string {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return ""
}

func (this *LabelPair) EqualVT(that *LabelPair) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Name, that.Name; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Value, that.Value; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *LabelPair) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*LabelPair)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Gauge) EqualVT(that *Gauge) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Value, that.Value; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Gauge) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Gauge)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Counter) EqualVT(that *Counter) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Value, that.Value; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if !this.Exemplar.EqualVT(that.Exemplar) {
		return false
	}
	if !this.CreatedTimestamp.EqualVT(that.CreatedTimestamp) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Counter) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Counter)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Quantile) EqualVT(that *Quantile) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Quantile, that.Quantile; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Value, that.Value; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Quantile) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Quantile)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Summary) EqualVT(that *Summary) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.SampleCount, that.SampleCount; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.SampleSum, that.SampleSum; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if len(this.Quantile) != len(that.Quantile) {
		return false
	}
	for i, vx := range this.Quantile {
		vy := that.Quantile[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Quantile{}
			}
			if q == nil {
				q = &Quantile{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if !this.CreatedTimestamp.EqualVT(that.CreatedTimestamp) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Summary) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Summary)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Untyped) EqualVT(that *Untyped) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Value, that.Value; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Untyped) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Untyped)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Histogram) EqualVT(that *Histogram) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.SampleCount, that.SampleCount; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.SampleSum, that.SampleSum; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if len(this.Bucket) != len(that.Bucket) {
		return false
	}
	for i, vx := range this.Bucket {
		vy := that.Bucket[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Bucket{}
			}
			if q == nil {
				q = &Bucket{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if p, q := this.SampleCountFloat, that.SampleCountFloat; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Schema, that.Schema; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.ZeroThreshold, that.ZeroThreshold; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.ZeroCount, that.ZeroCount; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.ZeroCountFloat, that.ZeroCountFloat; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if len(this.NegativeSpan) != len(that.NegativeSpan) {
		return false
	}
	for i, vx := range this.NegativeSpan {
		vy := that.NegativeSpan[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &BucketSpan{}
			}
			if q == nil {
				q = &BucketSpan{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if len(this.NegativeDelta) != len(that.NegativeDelta) {
		return false
	}
	for i, vx := range this.NegativeDelta {
		vy := that.NegativeDelta[i]
		if vx != vy {
			return false
		}
	}
	if len(this.NegativeCount) != len(that.NegativeCount) {
		return false
	}
	for i, vx := range this.NegativeCount {
		vy := that.NegativeCount[i]
		if vx != vy {
			return false
		}
	}
	if len(this.PositiveSpan) != len(that.PositiveSpan) {
		return false
	}
	for i, vx := range this.PositiveSpan {
		vy := that.PositiveSpan[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &BucketSpan{}
			}
			if q == nil {
				q = &BucketSpan{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if len(this.PositiveDelta) != len(that.PositiveDelta) {
		return false
	}
	for i, vx := range this.PositiveDelta {
		vy := that.PositiveDelta[i]
		if vx != vy {
			return false
		}
	}
	if len(this.PositiveCount) != len(that.PositiveCount) {
		return false
	}
	for i, vx := range this.PositiveCount {
		vy := that.PositiveCount[i]
		if vx != vy {
			return false
		}
	}
	if !this.CreatedTimestamp.EqualVT(that.CreatedTimestamp) {
		return false
	}
	if len(this.Exemplars) != len(that.Exemplars) {
		return false
	}
	for i, vx := range this.Exemplars {
		vy := that.Exemplars[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Exemplar{}
			}
			if q == nil {
				q = &Exemplar{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Histogram) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Histogram)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Bucket) EqualVT(that *Bucket) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.CumulativeCount, that.CumulativeCount; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.UpperBound, that.UpperBound; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if !this.Exemplar.EqualVT(that.Exemplar) {
		return false
	}
	if p, q := this.CumulativeCountFloat, that.CumulativeCountFloat; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Bucket) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Bucket)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *BucketSpan) EqualVT(that *BucketSpan) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Offset, that.Offset; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Length, that.Length; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *BucketSpan) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*BucketSpan)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Exemplar) EqualVT(that *Exemplar) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Label) != len(that.Label) {
		return false
	}
	for i, vx := range this.Label {
		vy := that.Label[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &LabelPair{}
			}
			if q == nil {
				q = &LabelPair{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if p, q := this.Value, that.Value; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if !this.Timestamp.EqualVT(that.Timestamp) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Exemplar) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Exemplar)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *Metric) EqualVT(that *Metric) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if len(this.Label) != len(that.Label) {
		return false
	}
	for i, vx := range this.Label {
		vy := that.Label[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &LabelPair{}
			}
			if q == nil {
				q = &LabelPair{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if !this.Gauge.EqualVT(that.Gauge) {
		return false
	}
	if !this.Counter.EqualVT(that.Counter) {
		return false
	}
	if !this.Summary.EqualVT(that.Summary) {
		return false
	}
	if !this.Untyped.EqualVT(that.Untyped) {
		return false
	}
	if p, q := this.TimestampMs, that.TimestampMs; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if !this.Histogram.EqualVT(that.Histogram) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *Metric) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*Metric)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
func (this *MetricFamily) EqualVT(that *MetricFamily) bool {
	if this == that {
		return true
	} else if this == nil || that == nil {
		return false
	}
	if p, q := this.Name, that.Name; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Help, that.Help; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if p, q := this.Type, that.Type; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	if len(this.Metric) != len(that.Metric) {
		return false
	}
	for i, vx := range this.Metric {
		vy := that.Metric[i]
		if p, q := vx, vy; p != q {
			if p == nil {
				p = &Metric{}
			}
			if q == nil {
				q = &Metric{}
			}
			if !p.EqualVT(q) {
				return false
			}
		}
	}
	if p, q := this.Unit, that.Unit; (p == nil && q != nil) || (p != nil && (q == nil || *p != *q)) {
		return false
	}
	return string(this.unknownFields) == string(that.unknownFields)
}

func (this *MetricFamily) EqualMessageVT(thatMsg any) bool {
	that, ok := thatMsg.(*MetricFamily)
	if !ok {
		return false
	}
	return this.EqualVT(that)
}
