// Copyright 2013 Prometheus Team
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// @generated by protoc-gen-es-lite unknown with parameter "target=ts,ts_nocheck=false"
// @generated from file github.com/aperturerobotics/go-prometheus-client-lite/client_model/go/metrics.proto (package io.prometheus.client, syntax proto2)
/* eslint-disable */

import type { MessageType, PartialFieldInfo } from '@aptre/protobuf-es-lite'
import {
  createEnumType,
  createMessageType,
  ScalarType,
} from '@aptre/protobuf-es-lite'
import { Timestamp } from '@aptre/protobuf-es-lite/google/protobuf/timestamp'

export const protobufPackage = 'io.prometheus.client'

/**
 * @generated from enum io.prometheus.client.MetricType
 */
export enum MetricType {
  /**
   * COUNTER must use the Metric field "counter".
   *
   * @generated from enum value: COUNTER = 0;
   */
  COUNTER = 0,

  /**
   * GAUGE must use the Metric field "gauge".
   *
   * @generated from enum value: GAUGE = 1;
   */
  GAUGE = 1,

  /**
   * SUMMARY must use the Metric field "summary".
   *
   * @generated from enum value: SUMMARY = 2;
   */
  SUMMARY = 2,

  /**
   * UNTYPED must use the Metric field "untyped".
   *
   * @generated from enum value: UNTYPED = 3;
   */
  UNTYPED = 3,

  /**
   * HISTOGRAM must use the Metric field "histogram".
   *
   * @generated from enum value: HISTOGRAM = 4;
   */
  HISTOGRAM = 4,

  /**
   * GAUGE_HISTOGRAM must use the Metric field "histogram".
   *
   * @generated from enum value: GAUGE_HISTOGRAM = 5;
   */
  GAUGE_HISTOGRAM = 5,
}

// MetricType_Enum is the enum type for MetricType.
export const MetricType_Enum = createEnumType(
  'io.prometheus.client.MetricType',
  [
    { no: 0, name: 'COUNTER' },
    { no: 1, name: 'GAUGE' },
    { no: 2, name: 'SUMMARY' },
    { no: 3, name: 'UNTYPED' },
    { no: 4, name: 'HISTOGRAM' },
    { no: 5, name: 'GAUGE_HISTOGRAM' },
  ],
)

/**
 * @generated from message io.prometheus.client.LabelPair
 */
export interface LabelPair {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string
  /**
   * @generated from field: optional string value = 2;
   */
  value?: string
}

// LabelPair contains the message type declaration for LabelPair.
export const LabelPair: MessageType<LabelPair> = createMessageType({
  typeName: 'io.prometheus.client.LabelPair',
  fields: [
    { no: 1, name: 'name', kind: 'scalar', T: ScalarType.STRING, opt: true },
    { no: 2, name: 'value', kind: 'scalar', T: ScalarType.STRING, opt: true },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Gauge
 */
export interface Gauge {
  /**
   * @generated from field: optional double value = 1;
   */
  value?: number
}

// Gauge contains the message type declaration for Gauge.
export const Gauge: MessageType<Gauge> = createMessageType({
  typeName: 'io.prometheus.client.Gauge',
  fields: [
    { no: 1, name: 'value', kind: 'scalar', T: ScalarType.DOUBLE, opt: true },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Exemplar
 */
export interface Exemplar {
  /**
   * @generated from field: repeated io.prometheus.client.LabelPair label = 1;
   */
  label?: LabelPair[]
  /**
   * @generated from field: optional double value = 2;
   */
  value?: number
  /**
   * @generated from field: optional google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Date
}

// Exemplar contains the message type declaration for Exemplar.
export const Exemplar: MessageType<Exemplar> = createMessageType({
  typeName: 'io.prometheus.client.Exemplar',
  fields: [
    {
      no: 1,
      name: 'label',
      kind: 'message',
      T: () => LabelPair,
      repeated: true,
    },
    { no: 2, name: 'value', kind: 'scalar', T: ScalarType.DOUBLE, opt: true },
    {
      no: 3,
      name: 'timestamp',
      kind: 'message',
      T: () => Timestamp,
      opt: true,
    },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Counter
 */
export interface Counter {
  /**
   * @generated from field: optional double value = 1;
   */
  value?: number
  /**
   * @generated from field: optional io.prometheus.client.Exemplar exemplar = 2;
   */
  exemplar?: Exemplar
  /**
   * @generated from field: optional google.protobuf.Timestamp created_timestamp = 3;
   */
  createdTimestamp?: Date
}

// Counter contains the message type declaration for Counter.
export const Counter: MessageType<Counter> = createMessageType({
  typeName: 'io.prometheus.client.Counter',
  fields: [
    { no: 1, name: 'value', kind: 'scalar', T: ScalarType.DOUBLE, opt: true },
    { no: 2, name: 'exemplar', kind: 'message', T: () => Exemplar, opt: true },
    {
      no: 3,
      name: 'created_timestamp',
      kind: 'message',
      T: () => Timestamp,
      opt: true,
    },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Quantile
 */
export interface Quantile {
  /**
   * @generated from field: optional double quantile = 1;
   */
  quantile?: number
  /**
   * @generated from field: optional double value = 2;
   */
  value?: number
}

// Quantile contains the message type declaration for Quantile.
export const Quantile: MessageType<Quantile> = createMessageType({
  typeName: 'io.prometheus.client.Quantile',
  fields: [
    {
      no: 1,
      name: 'quantile',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      opt: true,
    },
    { no: 2, name: 'value', kind: 'scalar', T: ScalarType.DOUBLE, opt: true },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Summary
 */
export interface Summary {
  /**
   * @generated from field: optional uint64 sample_count = 1;
   */
  sampleCount?: bigint
  /**
   * @generated from field: optional double sample_sum = 2;
   */
  sampleSum?: number
  /**
   * @generated from field: repeated io.prometheus.client.Quantile quantile = 3;
   */
  quantile?: Quantile[]
  /**
   * @generated from field: optional google.protobuf.Timestamp created_timestamp = 4;
   */
  createdTimestamp?: Date
}

// Summary contains the message type declaration for Summary.
export const Summary: MessageType<Summary> = createMessageType({
  typeName: 'io.prometheus.client.Summary',
  fields: [
    {
      no: 1,
      name: 'sample_count',
      kind: 'scalar',
      T: ScalarType.UINT64,
      opt: true,
    },
    {
      no: 2,
      name: 'sample_sum',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      opt: true,
    },
    {
      no: 3,
      name: 'quantile',
      kind: 'message',
      T: () => Quantile,
      repeated: true,
    },
    {
      no: 4,
      name: 'created_timestamp',
      kind: 'message',
      T: () => Timestamp,
      opt: true,
    },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Untyped
 */
export interface Untyped {
  /**
   * @generated from field: optional double value = 1;
   */
  value?: number
}

// Untyped contains the message type declaration for Untyped.
export const Untyped: MessageType<Untyped> = createMessageType({
  typeName: 'io.prometheus.client.Untyped',
  fields: [
    { no: 1, name: 'value', kind: 'scalar', T: ScalarType.DOUBLE, opt: true },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Bucket
 */
export interface Bucket {
  /**
   * @generated from field: optional uint64 cumulative_count = 1;
   */
  cumulativeCount?: bigint
  /**
   * @generated from field: optional double cumulative_count_float = 4;
   */
  cumulativeCountFloat?: number
  /**
   * @generated from field: optional double upper_bound = 2;
   */
  upperBound?: number
  /**
   * @generated from field: optional io.prometheus.client.Exemplar exemplar = 3;
   */
  exemplar?: Exemplar
}

// Bucket contains the message type declaration for Bucket.
export const Bucket: MessageType<Bucket> = createMessageType({
  typeName: 'io.prometheus.client.Bucket',
  fields: [
    {
      no: 1,
      name: 'cumulative_count',
      kind: 'scalar',
      T: ScalarType.UINT64,
      opt: true,
    },
    {
      no: 4,
      name: 'cumulative_count_float',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      opt: true,
    },
    {
      no: 2,
      name: 'upper_bound',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      opt: true,
    },
    { no: 3, name: 'exemplar', kind: 'message', T: () => Exemplar, opt: true },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.BucketSpan
 */
export interface BucketSpan {
  /**
   * @generated from field: optional sint32 offset = 1;
   */
  offset?: number
  /**
   * @generated from field: optional uint32 length = 2;
   */
  length?: number
}

// BucketSpan contains the message type declaration for BucketSpan.
export const BucketSpan: MessageType<BucketSpan> = createMessageType({
  typeName: 'io.prometheus.client.BucketSpan',
  fields: [
    { no: 1, name: 'offset', kind: 'scalar', T: ScalarType.SINT32, opt: true },
    { no: 2, name: 'length', kind: 'scalar', T: ScalarType.UINT32, opt: true },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Histogram
 */
export interface Histogram {
  /**
   * @generated from field: optional uint64 sample_count = 1;
   */
  sampleCount?: bigint
  /**
   * @generated from field: optional double sample_count_float = 4;
   */
  sampleCountFloat?: number
  /**
   * @generated from field: optional double sample_sum = 2;
   */
  sampleSum?: number
  /**
   * @generated from field: repeated io.prometheus.client.Bucket bucket = 3;
   */
  bucket?: Bucket[]
  /**
   * @generated from field: optional google.protobuf.Timestamp created_timestamp = 15;
   */
  createdTimestamp?: Date
  /**
   * @generated from field: optional sint32 schema = 5;
   */
  schema?: number
  /**
   * @generated from field: optional double zero_threshold = 6;
   */
  zeroThreshold?: number
  /**
   * @generated from field: optional uint64 zero_count = 7;
   */
  zeroCount?: bigint
  /**
   * @generated from field: optional double zero_count_float = 8;
   */
  zeroCountFloat?: number
  /**
   * @generated from field: repeated io.prometheus.client.BucketSpan negative_span = 9;
   */
  negativeSpan?: BucketSpan[]
  /**
   * @generated from field: repeated sint64 negative_delta = 10;
   */
  negativeDelta?: bigint[]
  /**
   * @generated from field: repeated double negative_count = 11;
   */
  negativeCount?: number[]
  /**
   * @generated from field: repeated io.prometheus.client.BucketSpan positive_span = 12;
   */
  positiveSpan?: BucketSpan[]
  /**
   * @generated from field: repeated sint64 positive_delta = 13;
   */
  positiveDelta?: bigint[]
  /**
   * @generated from field: repeated double positive_count = 14;
   */
  positiveCount?: number[]
  /**
   * @generated from field: repeated io.prometheus.client.Exemplar exemplars = 16;
   */
  exemplars?: Exemplar[]
}

// Histogram contains the message type declaration for Histogram.
export const Histogram: MessageType<Histogram> = createMessageType({
  typeName: 'io.prometheus.client.Histogram',
  fields: [
    {
      no: 1,
      name: 'sample_count',
      kind: 'scalar',
      T: ScalarType.UINT64,
      opt: true,
    },
    {
      no: 4,
      name: 'sample_count_float',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      opt: true,
    },
    {
      no: 2,
      name: 'sample_sum',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      opt: true,
    },
    { no: 3, name: 'bucket', kind: 'message', T: () => Bucket, repeated: true },
    {
      no: 15,
      name: 'created_timestamp',
      kind: 'message',
      T: () => Timestamp,
      opt: true,
    },
    { no: 5, name: 'schema', kind: 'scalar', T: ScalarType.SINT32, opt: true },
    {
      no: 6,
      name: 'zero_threshold',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      opt: true,
    },
    {
      no: 7,
      name: 'zero_count',
      kind: 'scalar',
      T: ScalarType.UINT64,
      opt: true,
    },
    {
      no: 8,
      name: 'zero_count_float',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      opt: true,
    },
    {
      no: 9,
      name: 'negative_span',
      kind: 'message',
      T: () => BucketSpan,
      repeated: true,
    },
    {
      no: 10,
      name: 'negative_delta',
      kind: 'scalar',
      T: ScalarType.SINT64,
      repeated: true,
    },
    {
      no: 11,
      name: 'negative_count',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      repeated: true,
    },
    {
      no: 12,
      name: 'positive_span',
      kind: 'message',
      T: () => BucketSpan,
      repeated: true,
    },
    {
      no: 13,
      name: 'positive_delta',
      kind: 'scalar',
      T: ScalarType.SINT64,
      repeated: true,
    },
    {
      no: 14,
      name: 'positive_count',
      kind: 'scalar',
      T: ScalarType.DOUBLE,
      repeated: true,
    },
    {
      no: 16,
      name: 'exemplars',
      kind: 'message',
      T: () => Exemplar,
      repeated: true,
    },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.Metric
 */
export interface Metric {
  /**
   * @generated from field: repeated io.prometheus.client.LabelPair label = 1;
   */
  label?: LabelPair[]
  /**
   * @generated from field: optional io.prometheus.client.Gauge gauge = 2;
   */
  gauge?: Gauge
  /**
   * @generated from field: optional io.prometheus.client.Counter counter = 3;
   */
  counter?: Counter
  /**
   * @generated from field: optional io.prometheus.client.Summary summary = 4;
   */
  summary?: Summary
  /**
   * @generated from field: optional io.prometheus.client.Untyped untyped = 5;
   */
  untyped?: Untyped
  /**
   * @generated from field: optional io.prometheus.client.Histogram histogram = 7;
   */
  histogram?: Histogram
  /**
   * @generated from field: optional int64 timestamp_ms = 6;
   */
  timestampMs?: bigint
}

// Metric contains the message type declaration for Metric.
export const Metric: MessageType<Metric> = createMessageType({
  typeName: 'io.prometheus.client.Metric',
  fields: [
    {
      no: 1,
      name: 'label',
      kind: 'message',
      T: () => LabelPair,
      repeated: true,
    },
    { no: 2, name: 'gauge', kind: 'message', T: () => Gauge, opt: true },
    { no: 3, name: 'counter', kind: 'message', T: () => Counter, opt: true },
    { no: 4, name: 'summary', kind: 'message', T: () => Summary, opt: true },
    { no: 5, name: 'untyped', kind: 'message', T: () => Untyped, opt: true },
    {
      no: 7,
      name: 'histogram',
      kind: 'message',
      T: () => Histogram,
      opt: true,
    },
    {
      no: 6,
      name: 'timestamp_ms',
      kind: 'scalar',
      T: ScalarType.INT64,
      opt: true,
    },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})

/**
 * @generated from message io.prometheus.client.MetricFamily
 */
export interface MetricFamily {
  /**
   * @generated from field: optional string name = 1;
   */
  name?: string
  /**
   * @generated from field: optional string help = 2;
   */
  help?: string
  /**
   * @generated from field: optional io.prometheus.client.MetricType type = 3;
   */
  type?: MetricType
  /**
   * @generated from field: repeated io.prometheus.client.Metric metric = 4;
   */
  metric?: Metric[]
  /**
   * @generated from field: optional string unit = 5;
   */
  unit?: string
}

// MetricFamily contains the message type declaration for MetricFamily.
export const MetricFamily: MessageType<MetricFamily> = createMessageType({
  typeName: 'io.prometheus.client.MetricFamily',
  fields: [
    { no: 1, name: 'name', kind: 'scalar', T: ScalarType.STRING, opt: true },
    { no: 2, name: 'help', kind: 'scalar', T: ScalarType.STRING, opt: true },
    { no: 3, name: 'type', kind: 'enum', T: MetricType_Enum, opt: true },
    { no: 4, name: 'metric', kind: 'message', T: () => Metric, repeated: true },
    { no: 5, name: 'unit', kind: 'scalar', T: ScalarType.STRING, opt: true },
  ] as readonly PartialFieldInfo[],
  packedByDefault: false,
})
